# Main
main:
  - name: "About"
    weight: 1
    hasChildren: true
  - name: "About NWB"
    weight: 1
    url: "/about-us"
    parent: About
  - name: "The Software Ecosystem"
    weight: 2
    url: "/"
    parent: About
  - name: "Team"
    weight: 3
    url: "/"
    parent: About
  - name: "Publications"
    weight: 4
    url: "/"
    parent: About
  - name: "Contact Us"
    weight: 5
    url: "/"
    parent: About
  
  - name: "Community"
    weight: 2
    hasChildren: true
  - name: "News"
    weight: 1
    url: /
    parent: Community
  - name: "Events"
    weight: 2
    url: /
    parent: Community
  - name: "A/V Tools"
    weight: 3
    url: /
    parent: Community
  - name: "Grants and Projects"
    weight: 4
    url: /
    parent: Community
  - name: "Working Groups"
    weight: 5
    url: /
    parent: Community

  - name: "Using NWB"
    weight: 3
    url: /
  - name: "Policies"
    weight: 4
    url: /

# Footer
### About
about:
  - name: "About NWB"  
    weight: 1
    url: "/"
  - name: "The Software Ecosystem"
    weight: 2
    url: "/"
  - name: "Team"
    weight: 3
    url: "/"
  - name: "Publications"
    weight: 4
    url: "/"
  - name: "Contact Us"
    weight: 5
    url: "/"

### Community
community:
  - name: "News"
    weight: 1
    url: "/"
  - name: "Events"
    weight: 2
    url: "/"
  - name: "Analysis and Visualization Tools.<br>NWB Enhancement Proposals"
    weight: 3
    url: "/"
  - name: "(remove Public Datagete)"
    weight: 4
    url: "/"
  - name: "(remove Labs Using NWB)"
    weight: 5
    url: "/"
  - name: "Grants and Projects"
    weight: 6
    url: "/"
  - name: "Working Groups"
    weight: 7
    url: "/"

### Legal
legal: 
  - name: "Privacy Plicy"
    weight: 1
    url: "/"
  - name: "Terms of Use"
    weight: 2
    url: "/"