# Main
main:
  - name: "About"
    weight: 1
    hasChildren: true
  - name: "Our Services"
    weight: 1
    url: /
    parent: About
  - name: "Community"
    weight: 2
    hasChildren: true
  - name: "Platform"
    weight: 1
    url: /
    parent: Community
  - name: "Using NWB"
    weight: 3
    url: /
  - name: "Policies"
    weight: 4
    url: /
