# Main
main:
  - name: "About"
    weight: 1
    hasChildren: true
  - name: "About NWB"
    weight: 1
    url: "about-us/"
    parent: About
  - name: "The Software Ecosystem"
    weight: 2
    url: "nwb-software/"
    parent: About
  - name: "Team"
    weight: 3
    url: "team/"
    parent: About
  - name: "Publications"
    weight: 4
    url: "publications/"
    parent: About
  - name: "Contact Us"
    weight: 5
    url: "/contact-us"
    parent: About
  
  - name: "Community"
    weight: 2
    hasChildren: true
  - name: "News"
    weight: 1
    url: "/news"
    parent: Community
  - name: "Events"
    weight: 2
    url: "/events"
    parent: Community
  - name: "A/V Tools"
    weight: 3
    url: "/av-tools"
    parent: Community
  - name: "Grants and Projects"
    weight: 4
    url: "/grants-and-projects"
    parent: Community
  - name: "Working Groups"
    weight: 5
    url: "/working-groups"
    parent: Community

  - name: "Using NWB"
    weight: 3
    url: "using-nwb/"
  - name: "Policies"
    weight: 4
    url: "privacy-policy/"

# Footer
### About
about:
  - name: "About NWB"  
    weight: 1
    url: "/about-us"
  - name: "The Software Ecosystem"
    weight: 2
    url: "/nwb-software"
  - name: "Team"
    weight: 3
    url: "/team"
  - name: "Publications"
    weight: 4
    url: "/publications"
  - name: "Contact Us"
    weight: 5
    url: "/contact-us"

### Community
community:
  - name: "News"
    weight: 1
    url: "/news"
  - name: "Events"
    weight: 2
    url: "/events"
  - name: "Analysis and Visualization Tools.<br>NWB Enhancement Proposals"
    weight: 3
    url: "/av-tools"
  - name: "(remove Public Datagete)"
    weight: 4
    url: "/"
  - name: "(remove Labs Using NWB)"
    weight: 5
    url: "/"
  - name: "Grants and Projects"
    weight: 6
    url: "/grants-and-projects"
  - name: "Working Groups"
    weight: 7
    url: "/working-groups"

### Legal
legal: 
  - name: "Privacy Policy"
    weight: 1
    url: "/privacy-policy"
  - name: "Terms of Use"
    weight: 2
    url: "/terms-of-use"