# Header
logo: "/images/logo.png"
cta:
  enable: true
  text: "Get Started"
  link: "https://nwb-overview.readthedocs.io/en/latest/"

# Footer
footer_logo: "/images/colored-logo.png"
copyright_text: "© Neurodata Without Borders - All Rights Reserved"
